# flake8: noqa

# import apis into api package
from singularity_memory_client_api.api.audit_api import AuditApi
from singularity_memory_client_api.api.bank_templates_api import BankTemplatesApi
from singularity_memory_client_api.api.banks_api import BanksApi
from singularity_memory_client_api.api.directives_api import DirectivesApi
from singularity_memory_client_api.api.documents_api import DocumentsApi
from singularity_memory_client_api.api.entities_api import EntitiesApi
from singularity_memory_client_api.api.files_api import FilesApi
from singularity_memory_client_api.api.memory_api import MemoryApi
from singularity_memory_client_api.api.mental_models_api import MentalModelsApi
from singularity_memory_client_api.api.monitoring_api import MonitoringApi
from singularity_memory_client_api.api.operations_api import OperationsApi
from singularity_memory_client_api.api.webhooks_api import WebhooksApi

